### ISSUE TITLE
Issue with `--save-trace-data` in Github runners

### ISSUE THREAD

**Issue by julio4** [foundry-rs/setup-snfoundry#29]
Scarb version `2.9.2`
Snforge version `0.35.1`
Setup-snfoundry version `4.0.0`

Within a Scarb project, with the correct versions set in `.tool-versions` and `Scarb.toml` at the root of the repository, the following Github action works fine:

```yml
name: Test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: foundry-rs/setup-snfoundry@v4
      - uses: software-mansion/setup-scarb@v1
      - run: snforge test
```

However, adding `--save-trace-data` to `snforge test`, while appending the following to `Scarb.toml`:

```toml
[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
```

```yml
name: Test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: foundry-rs/setup-snfoundry@v4
      - uses: software-mansion/setup-scarb@v1
      - run: snforge test --save-trace-data
```

Cause the action to fails during tests compilation, with no specific error:
```sh
Run snforge test --save-trace-data
    Updating crates.io index
 Downloading crates ...
// ...
   Compiling snforge_scarb_plugin v0.35.1 (/home/runner/.cache/scarb/registry/src/scarbs.xyz-9djtpev4jug5q/snforge_scarb_plugin-0.35.1)
    Finished `release` profile [optimized] target(s) in 1m 19s
   Compiling test(tests) tests v0.1.0 (/home/runner/work/.../Scarb.toml)
Error: The operation was canceled.
```

It works perfectly fine locally with the exact same configuration.

**Comment by franciszekjob** [comment]
Hi @julio4,
I've tried on same version of scarb and foundry, but couldn't reproduce the error.
Here's the workflow I've used:

```yml
name: Checks
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v5.0.0
        with:
          starknet-foundry-version: 0.35.1

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.9.2
          scarb-lock: ./Scarb.lock

      - name: Run tests
        run: snforge test --save-trace-data
```

You didn't specify tool-versions file or explicit version of forge/scarb, so that could be potential problem. Anyway, please take a look at the workflow, it should solve your problem.
